name: CI/CD

on:
  push:
    branches:
      - feature/*
      - fix/*
      - chore/*

jobs:
  create-pr:
    name: Create Pull Request to Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if PR already exists
        id: check-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}" | jq -r '.[0].id')

          echo "pr_exists=$PR_EXISTS" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.pr_exists == ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref_name }}
          title: "Automated PR: Merging ${{ github.ref_name }}"
          body: "This PR was automatically created by GitHub Actions to merge ${{ github.ref_name }} into main."

  lint-and-test:
    name: Lint and Test
    needs: create-pr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.8.1"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test
