name: CI/CD

on:
  push:
    branches:
      - feature/*
      - fix/*
      - chore/*

jobs:
  create-pr:
    name: Create Pull Request to Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if PR already exists
        id: check-pr
        uses: peter-evans/closed-pull-requests@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref_name }}
          base: main

      - name: Create Pull Request
        if: steps.check-pr.outputs.pr_found != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref_name }}
          title: "Automated PR: Merging ${{ github.ref_name }}"
          body: "This PR was automatically created by GitHub Actions to merge ${{ github.ref_name }} into main."

  lint-and-test:
    name: Lint and Test
    needs: create-pr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test
